import type { RoccoTextCatalog } from '../types';

export const spanishBaitShopText: RoccoTextCatalog['baitShop'] = {
  magazineLookLine: '\u00a1Es una Microman\u00eda!',
  toiletLookLines: ['Un v\u00e1ter.'],
  toiletReadLabel: 'Leer',
  toiletUseLabel: 'Usar',
  toiletStaySeatedLines: [
    'No, primero tengo que terminar esto.',
    'Ni hablar. Primero tengo que acabar aqu\u00ed.',
    'Antes de ir a ninguna parte, tengo que terminar esto.',
  ],
  toiletNeedMagazineLine: 'Ganas no me faltan, pero me gustar\u00eda tener algo que leer.',
  toiletMagazineReadingLines: [
    'PERO \u00bfQU\u00c9 DIABLOS?',
    '\u00bfC\u00d3MO? \u00bfESTE SOY YO?',
    '\u00a1ESTA REVISTA CUENTA MI VIDA!',
    'EXPLICA MI VIDA COMO SI...',
    'FUERA UN VIDEOJUEGO',
    'A ver, Rocco, tranquilo...',
    'Aqu\u00ed dice que la llave estaba escondida en el tarjetero.',
    '\u00a1A buenas horas, mangas verdes!',
    'Y que, si no he tra\u00eddo al menos uno de',
    'estos objetos, estoy muerto:',
    'una concha rosa...',
    'una ganz\u00faa dorada...',
    'una especie de colgante/reloj/medall\u00f3n redondo...',
    'otro objeto met\u00e1lico peque\u00f1o parecido a un anzuelo...',
    '\u00a1Mierda! Este juego es de los que se aprenden perdiendo.',
  ],
  toiletMagazineKnownStanLine: '\u00a1Y STAN DE AFUERA!',
  toiletMagazineUnknownStanLine: '\u00a1Y EL VIEJO DE AFUERA!',
  toiletPoliceAlertLine: '\u00a1Polic\u00eda! El ladr\u00f3n est\u00e1 en mi ba\u00f1o',
  toiletDoorOpenLabel: 'Abrir',
  toiletDoorCloseLabel: 'Cerrar',
  toiletDoorWalkLabel: 'Caminar',
  toiletDoorNeedsKeyLines: [
    'Es de esas puertas que solo se abren con una llave.',
    'Tiene pinta de ser de las que solo se abren con llave.',
    'S\u00ed, de las que no se abren sin llave.',
  ],
  toiletDoorOpenWithKeyLines: [
    'Creo que esa llave rara que llevo en el bolsillo podr\u00eda abrirla.',
    'Deber\u00eda probarla desde el inventario.',
  ],
  toiletDoorWrongKeyLines: [
    'Ninguna la abre.',
    'Parece que ninguna es de aqu\u00ed.',
    'No, ninguna encaja.',
  ],
  toiletDoorLookLines: [
    'Parece una puerta de madera.',
    'Una puerta de madera al fondo.',
    'Sí, eso parece una puerta de madera.',
    'Diría que es una puerta de madera.',
  ],
  toiletDoorLookWithKeyLines: [
    'Tiene una cerradura donde podr\u00eda encajar esa llave rara.',
    'Creo que podr\u00eda abrirla.',
    'Podr\u00eda usar la llave de mi inventario.',
  ],
  toiletDoorKickLine: 'No pienso hacer ruido.',
  shellCityLookLines: [
    'Cuando era joven quedaba con amigos en una Shell.',
    'Ahhh, el lugar adonde nunca llegaremos, Patricio.',
    'Un cartel de chapa, algo corroído por el clima del mar.',
  ],
  shellCityKnownStanLine: '¿Sabrá Stan que es mejor poner los carteles fuera?',
  shellCityUnknownStanLine: '¿Sabrá este hombre que es mejor poner los carteles fuera?',
  benchLookLines: [
    'Es un taburete. En un lado dice "By El Rata" y en el otro: "Fueron Los Boys".',
    'Un taburete de madera. No sé yo si me quiero sentar ahí.',
    'Eso no parece estar en venta.',
  ],
  benchKnownStanWaitLine: 'Supongo que ahí Stan pasa las horas esperando clientes.',
  benchUnknownStanWaitLine: 'Supongo que ahí el viejo pasa las horas esperando clientes.',
  benchJumpUpLine: 'Guau, no sabía que podía hacer eso.',
  benchGrabLines: [
    'No me apetece sacar las manos de los bolsillos.',
    '¿Y para qué quiero eso?',
    'Naaah.',
    'A veces me llama la atención cada estupidez.',
    'Taburete de palo, cuchillo de herrero.',
  ],
  benchKnownStanStealLine: 'Esto está lleno de cosas más interesantes que robarle a Stan.',
  benchUnknownStanStealLine: 'Esto está lleno de cosas más interesantes que robarle al viejo.',
  postcardRackLookLines: [
    'Son fotos de estas playas.',
    'Postales para turistas.',
    'Recuerdos que la gente se lleva.',
  ],
  postcardRackRevealLine: 'Espera, aquí arriba hay algo.',
  postcardRackKickLines: [
    'Mala idea. Creo que eso haría mucho ruido.',
    'No voy a patear eso.',
    '¡No es para patear!',
  ],
  postcardRackGrabLines: ['¿Para qué? No tengo a dónde llevarlas.'],
  souvenirTableLookLines: [
    'Una mesa llena de conchas, estrellas de mar y otros recuerdos.',
    'Cosas de playa colocadas como si fueran tesoros.',
    'Recuerdos mar\u00edtimos con ojos pegados y etiqueta de venta.',
  ],
  souvenirTableKnownStanLine:
    'Stan encuentra estas cosas en la playa, les pone ojos y las vende aqu\u00ed.',
  souvenirTableUnknownStanLine:
    'El viejo encuentra estas cosas en la playa, les pone ojos y las vende aqu\u00ed.',
  souvenirTableKickLines: [
    'No. Saldr\u00edan conchas volando por todas partes.',
    'Demasiado fr\u00e1gil para una patada.',
    'No voy a patear una mesa llena de recuerdos rompibles.',
  ],
  hiddenKeysCollectedLine: 'Otra llave. Me la guardo.',
  cashRegisterLookLines: [
    '¿Una caja mecánica? ¡Qué reliquia!',
    'El cajón está abierto.',
    'No parece tener dinero.',
  ],
  cashRegisterKnownStanOldLine: 'Parece vieja, como Stan.',
  cashRegisterUnknownStanOldLine: 'Parece vieja, como el viejo de fuera.',
  cashRegisterGrabLines: ['Está vacía; no tiene dinero.'],
  cashRegisterKnownStanPocketLine: 'Stan debe llevar el dinero en sus bolsillos.',
  cashRegisterUnknownStanPocketLine: 'El viejo debe llevar el dinero en sus bolsillos.',
  cashRegisterKickLines: ['¿Cómo voy a levantar el pie hasta ahí?'],
  cashRegisterKnownStanWakeLine: '¿Para qué? ¿Para despertar a Stan?',
  cashRegisterUnknownStanWakeLine: '¿Para qué? ¿Para despertar al viejo?',
  windowLookLines: [
    'Una ventana. Está tapada por fuera.',
    'Me recuerda a Windows Me: una ventana que no sirve para nada.',
  ],
  windowKnownStanClosedLine: 'Stan la ha cerrado por fuera.',
  windowUnknownStanClosedLine: 'Este tipo la ha cerrado por fuera.',
  windowKnownStanCleaningLine: 'Me pregunto cuánto tiempo se pasará Stan limpiando este sitio.',
  windowUnknownStanCleaningLine:
    'Me pregunto cuánto tiempo se pasará este tipo limpiando este sitio.',
  leftBarrelLookLines: [
    'Un barril decorativo.',
    'Creo que se vende como decoración.',
    'Un artículo típico de una tienda de recuerdos marítimos.',
    'Un barril, un tonel.',
    'Qué lástima no tener coche ni casa; si no, me lo llevaba.',
  ],
};
