import type { RoccoTextCatalog } from '../types';

export const spanishManifestText: RoccoTextCatalog['manifest'] = {
  title: 'ROCCO',
  description: 'Una aventura al estilo de los años 90',
  author: 'Rocco Studio',
  publisher: "Diego D'Onofrio",
  genre: 'Aventura',
  players: '1',
  tags: ['integrado', 'predeterminado', 'demo', 'rocco'],
};

export const spanishActionsText: RoccoTextCatalog['actions'] = {
  look: 'Mirar',
  grab: 'Coger',
  kick: 'Patear',
  talk: 'Hablar',
  inventory: 'Inventario',
  see: 'Ver',
  press: 'Presionar',
};

export const spanishDescriptionsText: RoccoTextCatalog['descriptions'] = {
  rocco: 'Rocco',
  guysprite: 'Guysprite',
  baitBucket: 'Cubeta de cebo',
  baitShopDoor: 'Puerta de la tienda de cebo',
  backRightDoor: 'Puerta del fondo a la derecha',
  toilet: 'Váter',
  bathroom: 'Baño',
  seatedRocco: 'Rocco en estado puro',
  shellCitySign: 'Cartel de Shell City',
  bench: 'Taburete',
  postcardRack: 'Postales',
  souvenirTable: 'Mesa de souvenirs',
  hiddenKeys: 'Llave escondida',
  cashRegister: 'Caja registradora',
  window: 'Ventana',
  barrel: 'Barril',
  keys: 'Llaves',
  magazine: 'Revista',
  micromania: 'Micromanía',
  oldMan: 'Viejo',
  stan: 'Stan',
  pelikan: 'Pel\u{ED}cano',
  intercomunicador: 'Intercomunicador',
  noisyMachine: 'M\u{E1}quina tremendamente ruidosa',
  shelf: 'Estanter\u{ED}a vac\u{ED}a',
  timbre: 'Timbre',
  doorHandle: 'Manija de la puerta',
  ascendingPipes: 'Tuber\u{ED}as ascendentes',
  wheelValve: 'V\u{E1}lvula de volante',
  shopExitDoorDescription: 'Puerta de salida',
  otherPierPart: 'Ir a la otra parte del muelle',
  otherShopPart: 'Ir a la otra parte de la tienda',
  exitBathroom: 'Salir del ba\u{F1}o',
  otherOfficePart: 'Ir a la otra parte de la oficina',
};

export const spanishLevelsText: RoccoTextCatalog['levels'] = {
  beginning: 'Comienzo del muelle',
  middle: 'Medio del muelle',
  end: 'Final del muelle',
  statusCartridge: 'Cartucho',
  statusLevel: 'Nivel',
  statusScene: 'Escena',
  baitShopPlaceholderTitle: 'Tienda de cebo',
  baitShopToiletTitle: 'Baño',
  resetOfficeTitle: 'Oficina del reset',
};

export const spanishDeveloperText: RoccoTextCatalog['developer'] = {
  actionLabel: 'Modo desarrollador',
  title: 'Modo desarrollador',
  jump: 'Saltar',
  inventory: 'Inventario',
  events: 'Alterar eventos',
  cycleSprite: 'Cambiar sprite',
  jumpLevelTitle: 'Saltar a nivel',
  jumpScreenTitle: 'Saltar a pantalla',
  eventLevelTitle: 'Elegir nivel',
  eventScreenTitle: 'Elegir pantalla',
  eventTitle: 'Elegir evento',
  pierLevelLabel: 'Muelle',
  resetOfficeSecondArrival: 'Oficina del reset 2 (entrada)',
  inventoryTitle: 'Inventario de desarrollador',
  add: 'Añadir',
  remove: 'Quitar',
  on: 'ON',
  off: 'OFF',
  putLabCoatEvent: 'Poner bata',
  removeLabCoatEvent: 'Quitar bata',
  allowToiletReuseEvent: 'Permitir usar váter más de una vez',
  clickToJumpStatus: 'Modo desarrollador: haz clic en cualquier parte para saltar.',
  clickToCycleSpriteStatus:
    'Modo desarrollador: haz clic en un sprite para cambiar su imagen. Haz clic fuera para salir.',
};
