export const ROCCO_PIER_START_LEVEL_ID = 'pier-start';
export const ROCCO_PIER_MIDDLE_LEVEL_ID = 'pier-middle';
export const ROCCO_PIER_END_LEVEL_ID = 'pier-end';
export const PIER_START_SCENE_ID = 'rocco-pier-start-scene';
export const PIER_MIDDLE_SCENE_ID = 'rocco-pier-middle-scene';
export const PIER_END_SCENE_ID = 'rocco-pier-end-scene';
export const DEFAULT_SCENE_ID = PIER_MIDDLE_SCENE_ID;
export const DEFAULT_DESIGN_WIDTH = 960;
export const DEFAULT_DESIGN_HEIGHT = 540;
export const DEFAULT_ROCCO_GREEN_BLACK = '#0f1610';
export const DEFAULT_BACKGROUND_IMAGE_WIDTH = 1672;
export const DEFAULT_BACKGROUND_IMAGE_HEIGHT = 941;
export const PIER_BACKGROUND_SCROLL_LEFT_X = 0;
export const PIER_BACKGROUND_SCROLL_CENTER_X =
  (DEFAULT_BACKGROUND_IMAGE_WIDTH - DEFAULT_DESIGN_WIDTH) / 2;
export const PIER_BACKGROUND_SCROLL_RIGHT_X = DEFAULT_BACKGROUND_IMAGE_WIDTH - DEFAULT_DESIGN_WIDTH;
export const DEFAULT_CENTERED_BACKGROUND_SCROLL_X = PIER_BACKGROUND_SCROLL_CENTER_X;
export const DEFAULT_CENTERED_BACKGROUND_SCROLL_Y =
  (DEFAULT_BACKGROUND_IMAGE_HEIGHT - DEFAULT_DESIGN_HEIGHT) / 2;
export const DEFAULT_WALK_MAP_ID = 'rocco-pier-walking-path';
export const DEFAULT_WALK_MAP_ALPHA_THRESHOLD = 16;
export const PIER_LEVEL_EXIT_TRIGGER_WIDTH = 24;
export const PIER_LEVEL_TRANSITION_COOLDOWN_MS = 450;
export const DEFAULT_WATER_EFFECT_COLORS = [
  '#106880',
  '#085058',
  '#084850',
  '#105860',
  '#085860',
  '#106068',
  '#187088',
  '#086078',
] as const;
export const DEFAULT_WATER_EFFECT_TOLERANCE = 0.08;
export const DEFAULT_WATER_EFFECT_AMPLITUDE = 5;
export const DEFAULT_WATER_EFFECT_WAVELENGTH = 30;
export const DEFAULT_WATER_EFFECT_SPEED = 2.1;
export const DEFAULT_WATER_EFFECT_STRENGTH = 0.75;
export const DEFAULT_CLOUD_SPRITE_DEFINITION_ID = 'rocco-cloud-sprite';
export const DEFAULT_CLOUD_SPRITE_INSTANCE_ID = 'rocco-cloud-main';
export const DEFAULT_CLOUD_SPRITE_ANIMATION_ID = 'cloud-idle';
export const DEFAULT_CLOUD_SPRITE_WIDTH = 372;
export const DEFAULT_CLOUD_SPRITE_HEIGHT = 171;
export const DEFAULT_CLOUD_SPRITE_SCALE = 0.5;
export const DEFAULT_CLOUD_SPRITE_OPACITY = 0.9;
export const DEFAULT_CLOUD_SCALE_GROWTH_FACTOR = 0.3;
export const DEFAULT_CLOUD_START_X = 140;
export const DEFAULT_CLOUD_WRAP_RIGHT_X = 980;
export const DEFAULT_CLOUD_BASE_Y = -8;
export const DEFAULT_CLOUD_VERTICAL_AMPLITUDE = 1;
export const DEFAULT_CLOUD_VERTICAL_PERIOD_MS = 12800;
export const DEFAULT_CLOUD_SPEED_X = 0.7;
export const DEFAULT_PELIKAN_SPRITE_DEFINITION_ID = 'rocco-pelikan-sprite';
export const DEFAULT_PELIKAN_SPRITE_INSTANCE_ID = 'rocco-pelikan-main';
export const DEFAULT_PELIKAN_FLIGHT_SOUND_ID = 'rocco-pelikan-flight-sound';
export const DEFAULT_PELIKAN_SPRITE_ANIMATION_ID = 'pelikan-idle';
export const DEFAULT_PELIKAN_FLIGHT_ANIMATION_ID = 'pelikan-flight';
export const DEFAULT_PELIKAN_FEEDING_ANIMATION_ID = 'pelikan-feeding';
export const DEFAULT_PELIKAN_FEEDING_WAIT_ANIMATION_ID = 'pelikan-feeding-wait';
export const DEFAULT_PELIKAN_SPRITE_WIDTH = 314;
export const DEFAULT_PELIKAN_SPRITE_HEIGHT = 377;
export const DEFAULT_PELIKAN_SHEET_WIDTH = 1448;
export const DEFAULT_PELIKAN_SHEET_HEIGHT = 1086;
export const DEFAULT_PELIKAN_SPRITE_SCALE = 0.42;
export const DEFAULT_PELIKAN_SPRITE_OPACITY = 1;
export const DEFAULT_PELIKAN_FRAME_DURATION_MS = 1000;
export const DEFAULT_PELIKAN_FLIGHT_FRAME_DURATION_MS = 95;
export const DEFAULT_PELIKAN_FEEDING_FRAME_DURATION_MS = 140;
export const DEFAULT_PELIKAN_MIN_FEEDING_WAIT_MS = 1000;
export const DEFAULT_PELIKAN_MAX_FEEDING_WAIT_MS = 3000;
export const DEFAULT_PELIKAN_TURN_DURATION_MS = 320;
export const DEFAULT_PELIKAN_FLIGHT_DURATION_MS = 1250;
export const DEFAULT_PELIKAN_FLIGHT_SOUND_VOLUME = 0.85;
export const DEFAULT_PELIKAN_MIN_POSE_DELAY_MS = 1000;
export const DEFAULT_PELIKAN_MAX_POSE_DELAY_MS = 5000;
export const DEFAULT_PELIKAN_PERCH_X = 835;
export const DEFAULT_PELIKAN_PERCH_Y = 311;
export const DEFAULT_PELIKAN_FEEDING_X = 235;
export const DEFAULT_PELIKAN_FEEDING_Y = 306;
export const DEFAULT_PELIKAN_FLIGHT_ARC_HEIGHT = 72;
export const DEFAULT_PELIKAN_FOOT_PIVOT_X = 178;
export const DEFAULT_PELIKAN_FOOT_PIVOT_Y = 354;
export const DEFAULT_PELIKAN_RENDER_LAYER = 'foreground';
export const DEFAULT_PELIKAN_FEEDING_RENDER_LAYER = 'world.actors';
export const DEFAULT_PELIKAN_Z_INDEX = 100;
export const DEFAULT_PELIKAN_FEEDING_Z_INDEX = 319;
export const DEFAULT_STAN_SPRITE_DEFINITION_ID = 'rocco-stan-sprite';
export const DEFAULT_STAN_SPRITE_INSTANCE_ID = 'rocco-stan-main';
export const DEFAULT_STAN_SLEEPING_ANIMATION_ID = 'stan-sleeping';
export const DEFAULT_STAN_SHEET_WIDTH = 1448;
export const DEFAULT_STAN_SHEET_HEIGHT = 1086;
export const DEFAULT_STAN_SPRITE_SCALE = 0.32;
export const DEFAULT_STAN_X = 734;
export const DEFAULT_STAN_Y = 326;
export const DEFAULT_STAN_RENDER_LAYER = 'world.actors';
export const DEFAULT_STAN_Z_INDEX = 16;
export const DEFAULT_KEYS_SPRITE_DEFINITION_ID = 'rocco-keys-sprite';
export const DEFAULT_KEYS_SPRITE_INSTANCE_ID = 'rocco-keys-main';
export const DEFAULT_KEYS_ANIMATION_ID = 'keys-idle';
export const DEFAULT_KEYS_SPRITE_WIDTH = 300;
export const DEFAULT_KEYS_SPRITE_HEIGHT = 400;
export const DEFAULT_KEYS_SPRITE_SCALE = 0.12;
export const DEFAULT_KEYS_PRESENTATION_PITCH_DEGREES = 45;
export const DEFAULT_KEYS_X = DEFAULT_PELIKAN_PERCH_X - 10;
export const DEFAULT_KEYS_Y = DEFAULT_PELIKAN_PERCH_Y + 20;
export const DEFAULT_KEYS_PIVOT_X = 150;
export const DEFAULT_KEYS_PIVOT_Y = 365;
export const DEFAULT_KEYS_RENDER_LAYER = 'foreground';
export const DEFAULT_KEYS_Z_INDEX = 95;
export const DEFAULT_BAIT_BUCKET_SPRITE_DEFINITION_ID = 'rocco-bait-bucket-sprite';
export const DEFAULT_BAIT_BUCKET_SPRITE_INSTANCE_ID = 'rocco-bait-bucket-main';
export const DEFAULT_BAIT_BUCKET_NORMAL_ANIMATION_ID = 'bait-bucket-normal';
export const DEFAULT_BAIT_BUCKET_DROPPED_ANIMATION_ID = 'bait-bucket-dropped';
export const DEFAULT_BAIT_BUCKET_SPRITE_WIDTH = 1254;
export const DEFAULT_BAIT_BUCKET_SPRITE_HEIGHT = 1254;
export const DEFAULT_BAIT_BUCKET_SCALE = 0.085;
export const DEFAULT_BAIT_BUCKET_X = 295;
export const DEFAULT_BAIT_BUCKET_Y = 318;
export const DEFAULT_BAIT_BUCKET_NORMAL_PIVOT_X = 621;
export const DEFAULT_BAIT_BUCKET_NORMAL_PIVOT_Y = 999;
export const DEFAULT_BAIT_BUCKET_DROPPED_PIVOT_X = 602;
export const DEFAULT_BAIT_BUCKET_DROPPED_PIVOT_Y = 968;
export const DEFAULT_BAIT_BUCKET_RENDER_LAYER = 'world.actors';
export const DEFAULT_BAIT_BUCKET_Z_INDEX = 20;
export const DEFAULT_SPRITE_DEFINITION_ID = 'rocco-running-demo-sprite';
export const DEFAULT_SPRITE_INSTANCE_ID = 'rocco-running-demo-main';
export const DEFAULT_SPRITE_IDLE_ACTION_ID = 'idle';
export const DEFAULT_SPRITE_RUN_ACTION_ID = 'run';
export const DEFAULT_SPRITE_PICK_UP_ACTION_ID = 'pick-up';
export const DEFAULT_SPRITE_STANDING_SEQUENCE_ANIMATION_ID = 'stand-sequence';
export const DEFAULT_SPRITE_STANDING_SEQUENCE_RIGHT_ANIMATION_ID = 'stand-sequence-right';
export const DEFAULT_SPRITE_FRAME_WIDTH = 300;
export const DEFAULT_SPRITE_FRAME_HEIGHT = 500;
export const DEFAULT_SPRITE_SCALE = 0.38;
export const PIER_PLAYER_ENTRY_MARGIN_X = 24;
export const PIER_PLAYER_LEFT_ENTRY_X = PIER_PLAYER_ENTRY_MARGIN_X;
export const PIER_PLAYER_RIGHT_ENTRY_X =
  DEFAULT_DESIGN_WIDTH -
  DEFAULT_SPRITE_FRAME_WIDTH * DEFAULT_SPRITE_SCALE -
  PIER_PLAYER_ENTRY_MARGIN_X;
export const DEFAULT_SPRITE_BASELINE = 486;
export const DEFAULT_SPRITE_GROUND_ANCHOR_X = 150;
export const DEFAULT_SPRITE_GROUND_ANCHOR_Y = DEFAULT_SPRITE_BASELINE;
export const DEFAULT_SPRITE_START_X = 980;
export const DEFAULT_SPRITE_CENTER_GROUND_X = DEFAULT_DESIGN_WIDTH / 2;
export const DEFAULT_SPRITE_PAUSE_X = Math.round(
  DEFAULT_SPRITE_CENTER_GROUND_X - DEFAULT_SPRITE_GROUND_ANCHOR_X * DEFAULT_SPRITE_SCALE,
);
export const DEFAULT_SPRITE_RUN_SPEED = 165;
export const DEFAULT_SPRITE_PIXELS_PER_FRAME = 46;
export const DEFAULT_SPRITE_STANDING_POSE_COUNT = 9;
export const DEFAULT_SPRITE_STANDING_POSE_DURATION_MS = 100;
export const DEFAULT_SPRITE_WALK_TOP_BASELINE_Y = 320;
export const DEFAULT_SPRITE_WALK_BOTTOM_BASELINE_Y = 360;
export const DEFAULT_SPRITE_WALK_TOP_Y = Math.round(
  DEFAULT_SPRITE_WALK_TOP_BASELINE_Y - DEFAULT_SPRITE_BASELINE * DEFAULT_SPRITE_SCALE,
);
export const DEFAULT_SPRITE_WALK_BOTTOM_Y = Math.round(
  DEFAULT_SPRITE_WALK_BOTTOM_BASELINE_Y - DEFAULT_SPRITE_BASELINE * DEFAULT_SPRITE_SCALE,
);
export const DEFAULT_SPRITE_Y_VALUES = [
  DEFAULT_SPRITE_WALK_TOP_Y + 15,
  DEFAULT_SPRITE_WALK_TOP_Y + 30,
  DEFAULT_SPRITE_WALK_TOP_Y,
  DEFAULT_SPRITE_WALK_BOTTOM_Y,
];
