export const PIER_PELIKAN_CONFIG = {
  spriteDefinitionId: 'rocco-pelikan-sprite' as const,
  spriteInstanceId: 'rocco-pelikan-main' as const,
  flightSoundId: 'rocco-pelikan-flight-sound' as const,
  spriteAnimationId: 'pelikan-idle' as const,
  flightAnimationId: 'pelikan-flight' as const,
  feedingAnimationId: 'pelikan-feeding' as const,
  feedingWaitAnimationId: 'pelikan-feeding-wait' as const,
  spriteWidth: 314,
  spriteHeight: 377,
  sheetWidth: 1448,
  sheetHeight: 1086,
  spriteScale: 0.42,
  spriteOpacity: 1,
  frameDurationMs: 1000,
  flightFrameDurationMs: 95,
  feedingFrameDurationMs: 140,
  minFeedingWaitMs: 1000,
  maxFeedingWaitMs: 3000,
  turnDurationMs: 320,
  flightDurationMs: 1250,
  flightSoundVolume: 0.85,
  minPoseDelayMs: 1000,
  maxPoseDelayMs: 5000,
  perchX: 835,
  perchY: 311,
  feedingX: 235,
  feedingY: 306,
  flightArcHeight: 72,
  footPivotX: 178,
  footPivotY: 354,
  renderLayer: 'foreground' as const,
  feedingRenderLayer: 'world.actors' as const,
  zIndex: 100,
  feedingZIndex: 319,
};
