import { ROCCO_PLAYER_CONFIG } from '../../player';
import { ROCCO_DESIGN_WIDTH, ROCCO_DESIGN_HEIGHT } from '../../game-design';

export const PIER_BACKGROUND_IMAGE_WIDTH = 1672;
export const PIER_BACKGROUND_IMAGE_HEIGHT = 941;

export const PIER_BACKGROUND_SCROLL_LEFT_X = 0;
export const PIER_BACKGROUND_SCROLL_CENTER_X =
  (PIER_BACKGROUND_IMAGE_WIDTH - ROCCO_DESIGN_WIDTH) / 2;
export const PIER_BACKGROUND_SCROLL_RIGHT_X = PIER_BACKGROUND_IMAGE_WIDTH - ROCCO_DESIGN_WIDTH;

export const PIER_CENTERED_BACKGROUND_SCROLL_X = PIER_BACKGROUND_SCROLL_CENTER_X;
export const PIER_CENTERED_BACKGROUND_SCROLL_Y =
  (PIER_BACKGROUND_IMAGE_HEIGHT - ROCCO_DESIGN_HEIGHT) / 2;

export const PIER_WALK_MAP_ID = 'rocco-pier-walking-path';
export const PIER_WALK_MAP_ALPHA_THRESHOLD = 16;

export const PIER_LEVEL_TRANSITION_COOLDOWN_MS = 450;

export const PIER_PLAYER_ENTRY_MARGIN_X = 24;
export const PIER_PLAYER_LEFT_ENTRY_X = PIER_PLAYER_ENTRY_MARGIN_X;
export const PIER_PLAYER_RIGHT_ENTRY_X =
  ROCCO_DESIGN_WIDTH -
  ROCCO_PLAYER_CONFIG.frame.width * ROCCO_PLAYER_CONFIG.motion.scale -
  PIER_PLAYER_ENTRY_MARGIN_X;

export const PIER_LEVEL_EXIT_TRIGGER_WIDTH = Math.round(
  PIER_PLAYER_ENTRY_MARGIN_X +
    ROCCO_PLAYER_CONFIG.frame.groundAnchor.x * ROCCO_PLAYER_CONFIG.motion.scale,
);
