import type { RoccoTextCatalog } from '../types';

export const englishBaitShopText: RoccoTextCatalog['baitShop'] = {
  magazineLookLine: "It's a Micromania!",
  toiletLookLines: ['A toilet.'],
  toiletReadLabel: 'Read',
  toiletUseLabel: 'Use',
  toiletStaySeatedLines: [
    'No. I need to finish this first.',
    'Not yet. First I need to finish this.',
    'I am not getting up until I am done here.',
  ],
  toiletNeedMagazineLine: 'I definitely feel like it, but I would like to have something to read.',
  toiletUrgentLine: 'Not now. I need to hurry.',
  toiletMagazineReadingIntroLines: [
    'BUT WHAT THE HELL?',
    'HOW? IS THIS ME?',
    'THIS MAGAZINE HAS MY LIFE!!!',
    'IT EXPLAINS MY LIFE LIKE...',
    'IT WAS A VIDEO GAME',
    'Okay, Rocco, calm down....',
    'It says here the key was hidden in the card display.',
    'I should have read the magazine earlier!',
  ],
  toiletMagazineReadingMissingRelicLines: [
    'And if I did not bring the Coral Relic, I am dead.',
    'It says the Coral Relic is made with: a Floating Amulet...',
    '...which is made by hooking the Japanese float onto a...',
    '...beach necklace, and then putting a...',
    '...Turritella Razor into it to make the Abyssal Talisman....',
    '...but the Abyssal Talisman is incomplete without...',
    '...its red coral on the tip.',
    'It says here I am dead...',
  ],
  toiletMagazineReadingCoralRelicLines: [
    'It says here I need to stand up....',
    '....grab the Coral Relic quickly...',
    '....make a wish and break it: One talisman one wish',
  ],
  toiletMagazineKnownStanLine: 'AND STAN OUTSIDE!',
  toiletMagazineUnknownStanLine: 'AND THE OLD MAN OUTSIDE!',
  coralRelicStepLabel: 'Step On',
  coralRelicWishExistLine: 'I wish I had never existed',
  coralRelicWishRootLine: 'I wish to know the root of all this',
  coralRelicWishKnownStanDisappearLine: 'I wish Stan would disappear',
  coralRelicWishUnknownStanDisappearLine: 'I wish the old man would disappear',
  coralRelicWishEscapeLine: 'I wish I could escape from here',
  toiletPoliceAlertLine: 'Police! The thief is in my bathroom!',
  toiletPostWishPoliceWarningLine:
    'Come out of there immediately. Do not make me break the door down.',
  toiletPostWishReplyMomentPleaseLine: 'One moment please.',
  toiletPostWishReplyNoHitLine: 'You are not going to hit me, right?',
  toiletPostWishReplyWhatIfNotLine: 'And if I do not come out, then what?',
  toiletPostWishReplyComeInLine: 'Come in yourself if you are so brave',
  toiletPostWishPoliceResponseLine: 'Stop making this harder and come out now!',
  toiletDoorOpenLabel: 'Open',
  toiletDoorCloseLabel: 'Close',
  toiletDoorWalkLabel: 'Walk',
  toiletDoorNeedsKeyLines: [
    'That is one of those doors that only open with a key.',
    'It looks like the kind of door that only opens with a key.',
    'Yes, this is definitely one of those key-only doors.',
  ],
  toiletDoorOpenWithKeyLines: [
    'I think that strange key in my pocket could open this.',
    'I should try it from my inventory.',
  ],
  toiletDoorWrongKeyLines: [
    'None of these opens it.',
    'Looks like none of these belongs here.',
    'No. None of these fits this door.',
  ],
  toiletDoorLookLines: [
    'Looks like a wooden door.',
    'A wooden door at the back.',
    'Yes, that looks like a wooden door.',
    'I would say that is a wooden door.',
  ],
  toiletDoorLookWithKeyLines: [
    'There is a lock where that strange key might fit.',
    'I think I could open it.',
    'I could use the key from my inventory.',
  ],
  toiletDoorKickLine: 'I am not planning to make noise.',
  shellCityLookLines: [
    'When I was younger I used to meet friends at a Shell station.',
    'Ahhh, the place we will never reach, Patrick.',
    'A metal sign, a little weathered by the sea air.',
  ],
  shellCityKnownStanLine: 'Do you think Stan knows signs work better outside?',
  shellCityUnknownStanLine: 'Do you think this man knows signs work better outside?',
  benchLookLines: [
    'It is a stool. On one side it says "By El Rata" and on the other: "It Was The Boys".',
    'A wooden stool. I am not sure I want to sit there.',
    'That does not look like it is for sale.',
  ],
  benchKnownStanWaitLine: 'I suppose that is where Stan spends hours waiting for customers.',
  benchUnknownStanWaitLine:
    'I suppose that is where the old man spends hours waiting for customers.',
  benchJumpUpLine: 'Wow, I did not know I could do that.',
  benchGrabLines: [
    'I do not feel like taking my hands out of my pockets.',
    'And what would I want that for?',
    'Naaah.',
    'Sometimes the stupidest things catch my attention.',
    "Wooden stool, blacksmith's knife.",
  ],
  benchKnownStanStealLine:
    'This place is full of more interesting things than stealing that from Stan.',
  benchUnknownStanStealLine:
    'This place is full of more interesting things than stealing that from the old man.',
  postcardRackLookLines: [
    'They are photos of these beaches.',
    'Postcards for tourists.',
    'Souvenirs people take with them.',
  ],
  postcardRackRevealLine: 'Wait, there is something up here.',
  postcardRackKickLines: [
    'Bad idea, that would probably make a lot of noise.',
    'I am not going to kick that.',
    'That is not for kicking.',
  ],
  postcardRackGrabLines: ['What for? I do not have anywhere to take them.'],
  souvenirTableLookLines: [
    'A table full of shells, starfish, and other beach souvenirs.',
    'Bits and pieces from the shore, arranged like little treasures.',
    'Sea things with glued-on eyes and a price tag.',
  ],
  souvenirTableKnownStanLine:
    'Stan finds these on the beach, puts eyes on them, and sells them here.',
  souvenirTableUnknownStanLine:
    'The old man finds these on the beach, puts eyes on them, and sells them here.',
  souvenirTableKickLines: [
    'No. That would send shells flying everywhere.',
    'Too fragile for a kick.',
    'I am not kicking a table full of breakable souvenirs.',
  ],
  hiddenKeysCollectedLine: 'More keys. I will keep them.',
  cashRegisterLookLines: [
    'A mechanical cash register? What a relic.',
    'The drawer is open.',
    'It does not seem to have any money.',
  ],
  cashRegisterKnownStanOldLine: 'It looks old, like Stan.',
  cashRegisterUnknownStanOldLine: 'It looks old, like the old man outside.',
  cashRegisterGrabLines: ['It is empty. There is no money in it.'],
  cashRegisterKnownStanPocketLine: 'Stan must carry the money in his pockets.',
  cashRegisterUnknownStanPocketLine: 'The old man must carry the money in his pockets.',
  cashRegisterKickLines: ['How am I supposed to lift my foot up there?'],
  cashRegisterKnownStanWakeLine: 'What for? To wake Stan up?',
  cashRegisterUnknownStanWakeLine: 'What for? To wake the old man up?',
  windowLookLines: [
    'A window, blocked from the outside.',
    'It reminds me of Windows Me: a window that is useless.',
  ],
  windowKnownStanClosedLine: 'Stan shut it from the outside.',
  windowUnknownStanClosedLine: 'This man shut it from the outside.',
  windowKnownStanCleaningLine: 'I wonder how long Stan spends cleaning this place.',
  windowUnknownStanCleaningLine: 'I wonder how long this man spends cleaning this place.',
  leftBarrelLookLines: [
    'A decorative barrel.',
    'I think it is for sale as decoration.',
    'A typical item for a maritime souvenir shop.',
    'A barrel, a cask.',
    'What a shame I do not have a car or a house, or I would take it with me.',
  ],
};
