import type { RoccoTextCatalog } from '../types';

export const englishBaitShopText: RoccoTextCatalog['baitShop'] = {
  magazineLookLine: "It's a Micromania!",
  toiletLookLines: ['A toilet.'],
  toiletReadLabel: 'Read',
  toiletUseLabel: 'Use',
  toiletNeedMagazineLine: 'I definitely feel like it, but I would like to have something to read.',
  toiletMagazineReadingLines: [
    'BUT WHAT THE HELL?',
    'HOW? IS THIS ME?',
    'THIS MAGAZINE HAS MY LIFE!!!',
    'IT EXPLAINS MY LIFE LIKE...',
    'IT WAS A VIDEO GAME',
    'Okay, Rocco, calm down....',
    'It says here the key was hidden in the card rack',
    'Great timing. Just perfect!',
    'And if I have not brought at least one of',
    'these objects, I am dead:',
    'A pink shell...',
    'golden lockpick...',
    'some kind of round pendant/watch/medallion...',
    'another small metallic thing like a hook...',
    'Damn! This is one of those games you learn by losing.',
  ],
  toiletMagazineKnownStanLine: 'AND STAN OUTSIDE!',
  toiletMagazineUnknownStanLine: 'AND THE OLD MAN OUTSIDE!',
  toiletDoorOpenLabel: 'Open',
  toiletDoorCloseLabel: 'Close',
  toiletDoorWalkLabel: 'Walk',
  toiletDoorNeedsKeyLines: [
    'That is one of those doors that only open with a key.',
    'It looks like the kind of door that only opens with a key.',
    'Yes, this is definitely one of those key-only doors.',
  ],
  toiletDoorWrongKeyLines: [
    'None of these opens it.',
    'Looks like none of these belongs here.',
    'No. None of these fits this door.',
  ],
  toiletDoorLookLines: [
    'Looks like a wooden door.',
    'A wooden door at the back.',
    'Yes, that looks like a wooden door.',
    'I would say that is a wooden door.',
  ],
  toiletDoorKickLine: 'I am not planning to make noise.',
  shellCityLookLines: [
    'When I was younger I used to meet friends at a Shell station.',
    'Ahhh, the place we will never reach, Patrick.',
    'A metal sign, a little weathered by the sea air.',
  ],
  shellCityKnownStanLine: 'Do you think Stan knows signs work better outside?',
  shellCityUnknownStanLine: 'Do you think this man knows signs work better outside?',
  benchLookLines: [
    'It is a stool. On one side it says "By El Rata" and on the other: "It Was The Boys".',
    'A wooden stool. I am not sure I want to sit there.',
    'That does not look like it is for sale.',
  ],
  benchKnownStanWaitLine: 'I suppose that is where Stan spends hours waiting for customers.',
  benchUnknownStanWaitLine:
    'I suppose that is where the old man spends hours waiting for customers.',
  benchJumpUpLine: 'Wow, I did not know I could do that.',
  benchGrabLines: [
    'I do not feel like taking my hands out of my pockets.',
    'And what would I want that for?',
    'Naaah.',
    'Sometimes the stupidest things catch my attention.',
    "Wooden stool, blacksmith's knife.",
  ],
  benchKnownStanStealLine:
    'This place is full of more interesting things than stealing that from Stan.',
  benchUnknownStanStealLine:
    'This place is full of more interesting things than stealing that from the old man.',
  postcardRackLookLines: [
    'They are photos of these beaches.',
    'Postcards for tourists.',
    'Souvenirs people take with them.',
  ],
  postcardRackRevealLine: 'Wait, there is something up here.',
  postcardRackKickLines: [
    'Bad idea, that would probably make a lot of noise.',
    'I am not going to kick that.',
    'That is not for kicking.',
  ],
  postcardRackGrabLines: ['What for? I do not have anywhere to take them.'],
  hiddenKeysCollectedLine: 'More keys. I will keep them.',
  cashRegisterLookLines: [
    'A mechanical cash register? What a relic.',
    'The drawer is open.',
    'It does not seem to have any money.',
  ],
  cashRegisterKnownStanOldLine: 'It looks old, like Stan.',
  cashRegisterUnknownStanOldLine: 'It looks old, like the old man outside.',
  cashRegisterGrabLines: ['It is empty. There is no money in it.'],
  cashRegisterKnownStanPocketLine: 'Stan must carry the money in his pockets.',
  cashRegisterUnknownStanPocketLine: 'The old man must carry the money in his pockets.',
  cashRegisterKickLines: ['How am I supposed to lift my foot up there?'],
  cashRegisterKnownStanWakeLine: 'What for? To wake Stan up?',
  cashRegisterUnknownStanWakeLine: 'What for? To wake the old man up?',
  windowLookLines: [
    'A window, blocked from the outside.',
    'It reminds me of Windows Me: a window that is useless.',
  ],
  windowKnownStanClosedLine: 'Stan shut it from the outside.',
  windowUnknownStanClosedLine: 'This man shut it from the outside.',
  windowKnownStanCleaningLine: 'I wonder how long Stan spends cleaning this place.',
  windowUnknownStanCleaningLine: 'I wonder how long this man spends cleaning this place.',
  leftBarrelLookLines: [
    'A decorative barrel.',
    'I think it is for sale as decoration.',
    'A typical item for a maritime souvenir shop.',
    'A barrel, a cask.',
    'What a shame I do not have a car or a house, or I would take it with me.',
  ],
};
