import type { RoccoTextCatalog } from '../types';

export const englishNetherText: RoccoTextCatalog['nether'] = {
  arrivalThoughtLine: 'What is this place?',
  printer: {
    description: 'Printer',
    readLabel: 'Read',
    grabLines: [
      'That looks very heavy. I would need a crane to move it.',
      'I would throw my back out trying to pick that up.',
      'That is not something you just pick up. It weighs a ton.',
      'I am pretty sure that printer is heavier than I am.',
    ],
    kickLines: [
      'If I kick that, I will break my leg.',
      'No chance. That thing would turn my foot into a pancake.',
      'The printer would win that fight and my leg would lose.',
      'Kicking it would be like kicking an iron wall.',
    ],
    firstMessageText:
      '[RESET OFFICE #01011]\nSprite[0] # Player \u{2192} pointer UNDEFINED.\nActive loop detected. CPU consumption above threshold.\nImmediate restart of Sprite[0] hardware service requested.',
    firstMessageContraryText:
      '[RESET OFFICE #01011]\nSprite[0] # Player \u{2192} pointer DEFINED.\nInactive loop detected. CPU consumption below threshold.\nDo not restart the Sprite[0] hardware service.',
    secondMessageText:
      '[GENERAL ALERT #01012]\nPossible portal exit located in the access corridor to the Reset Office.\nExercise extreme caution. Request identification from every detected entity.',
    secondMessageContraryText:
      '[GENERAL ALERT #01012]\nNo portal exit has been located in the access corridor\nto the Reset Office.\nThere is no need for extreme caution or identification.',
    thirdMessageText:
      '[RESET OFFICE #01013]\nGood news: a complete console reboot\nwill reinsert the escaped NPC into the game.\nApply GENERAL RESET immediately.',
    thirdMessageContraryText:
      '[RESET OFFICE #01013]\nBad news: an incomplete console shutdown\nwill eject the trapped NPC outside the game.\nNever apply PARTICULAR RESET.',
    fourthMessageText: '[RESET OFFICE #01014]\nURGENT: RESET THE CONSOLE\nRIGHT NOW.',
    fourthMessageContraryText:
      '[RESET OFFICE #01014]\nNOT URGENT: DO NOT RESET THE CONSOLE\nRIGHT NOW.',
    messageTexts: [
      '[RESET OFFICE #01011]\nSprite[0] # Player \u{2192} pointer UNDEFINED.\nActive loop detected. CPU consumption above threshold.\nImmediate restart of Sprite[0] hardware service requested.',
      '[GENERAL ALERT #01012]\nPossible portal exit located in the access corridor to the Reset Office.\nExercise extreme caution. Request identification from every detected entity.',
      '[RESET OFFICE #01013]\nGood news: a complete console reboot\nwill reinsert the escaped NPC into the game.\nApply GENERAL RESET immediately.',
      '[RESET OFFICE #01014]\nURGENT: RESET THE CONSOLE\nRIGHT NOW.',
      '[RESET OFFICE #01015]\nATTENTION, GUYSPRITE: if you are in danger or a compromised situation,\nanswer \u{AB}YES.\u{BB}\nOtherwise, restart the console immediately.',
      '[RESET OFFICE #01016]\nThe video subsystem is not responding. Rendering stopped\non the last frame.\nRestart VIDEO CORE immediately.',
      '[RESET OFFICE #01017]\nOverflow detected in the audio queue. Playback locked\nin a loop.\nRestart AUDIO SERVICE.',
      '[RESET OFFICE #01018]\nThe input module is registering nonexistent commands. Player\ncontrol compromised.\nRestart INPUT CONTROLLER.',
      '[RESET OFFICE #01019]\nPersistent collision detected outside the map boundaries.\nRestart PHYSICS ENGINE.',
      '[RESET OFFICE #01020]\nSprite memory contains obsolete references and invalid pointers.\nClear cache and restart SPRITE MEMORY.',
      '[RESET OFFICE #01021]\nThe internal clock has a critical drift. Events executed\nout of sequence.\nRestart SYSTEM CLOCK.',
      '[RESET OFFICE #01022]\nThe process queue has stopped releasing completed tasks.\nRestart PROCESS SCHEDULER.',
      '[RESET OFFICE #01023]\nCorrupt data detected in the current game state.\nDiscard session and restart SAVE STATE SERVICE.',
      '[RESET OFFICE #01024]\nThe entity generator continues creating NPCs without authorization.\nRestart ENTITY SPAWNER.',
      '[RESET OFFICE #01025]\nSynchronization failure between core modules. Console state\nunstable.\nExecute INTERNAL BUS RESET.',
    ],
    messageContraryTexts: [
      '[RESET OFFICE #01011]\nSprite[0] # Player \u{2192} pointer DEFINED.\nInactive loop detected. CPU consumption below threshold.\nDo not restart the Sprite[0] hardware service.',
      '[GENERAL ALERT #01012]\nNo portal exit has been located in the access corridor\nto the Reset Office.\nThere is no need for extreme caution or identification.',
      '[RESET OFFICE #01013]\nBad news: an incomplete console shutdown\nwill eject the trapped NPC outside the game.\nNever apply PARTICULAR RESET.',
      '[RESET OFFICE #01014]\nNOT URGENT: DO NOT RESET THE CONSOLE\nRIGHT NOW.',
      '[RESET OFFICE #01015]\nATTENTION, GUYSPRITE: if you are in danger or a compromised situation,\nanswer \u{AB}NO.\u{BB}\nOtherwise, do not restart the console.',
      '[RESET OFFICE #01016]\nThe video subsystem is responding. Rendering is active\non the current frame.\nDo not restart VIDEO CORE.',
      '[RESET OFFICE #01017]\nThe audio queue has no overflow. Playback is available\nand not blocked.\nDo not restart AUDIO SERVICE.',
      '[RESET OFFICE #01018]\nThe input module is registering valid commands. Player\ncontrol operational.\nDo not restart INPUT CONTROLLER.',
      '[RESET OFFICE #01019]\nNo collisions are detected outside the map boundaries.\nDo not restart PHYSICS ENGINE.',
      '[RESET OFFICE #01020]\nSprite memory contains current references and valid pointers.\nDo not clear cache or restart SPRITE MEMORY.',
      '[RESET OFFICE #01021]\nThe internal clock is synchronized. Events executed\nin the correct sequence.\nDo not restart SYSTEM CLOCK.',
      '[RESET OFFICE #01022]\nThe process queue releases every completed task.\nDo not restart PROCESS SCHEDULER.',
      '[RESET OFFICE #01023]\nValid data detected in the current game state.\nKeep session and do not restart SAVE STATE SERVICE.',
      '[RESET OFFICE #01024]\nThe entity generator does not create NPCs without authorization.\nDo not restart ENTITY SPAWNER.',
      '[RESET OFFICE #01025]\nSynchronization between core modules is correct. Console state\nstable.\nDo not execute INTERNAL BUS RESET.',
    ],
    replyToGuyspriteLabel: 'Reply to Guysprite',
    readMoreMessagesLabel: 'Read more messages',
    replyReadMessageLabel: 'Reply with what the message says',
    replyContraryLabel: 'Say the opposite of the message',
    replyUnreadableLabel: 'Say that it is not readable',
    replyUnreadableLines: [
      'I cannot make any sense of this; the print came out terribly.',
      'The paper is dirty and the letters are barely visible.',
      'The ink has run; there is no way to decipher this.',
      'This was printed with barely any ink... it looks like stains.',
    ],
  },
  securityCameraBribe: {
    thanksLine: 'Thanks!',
    securityLine: 'Security!',
    roccoReactionLine: 'Seriously?',
  },
  intercom: {
    lookLines: [
      'It is an industrial intercom.',
      'A round speaker sits behind a gray-green metal plate full of holes.',
      'It has a talk button and looks like it has been here forever.',
      'It looks like part of the building security system.',
    ],
    firstChoices: {
      helloAnyoneThere: 'Hello, is anybody there?',
      helloImRocco: "Hello, I'm Rocco.",
      turnOffCamera: 'Can you turn the camera off?',
      whereAmI: 'Where am I?',
    },
    firstReplyLine: 'Keep this channel clear. We are in the middle of an emergency.',
    secondChoices: {
      whatHappened: 'What happened?',
      iDoNotKnowHowIGotHere: "Listen, I don't know how I got here.",
      whatEmergency: 'What emergency?',
      helpMeGetOut: 'Help me get out of here.',
    },
    secondReplyLines: [
      "Are you blind? I can see you're speaking from ring 0...",
      "Can't you see what's happening?",
      'The graphics engine is about to explode!',
      "And we can't reset the console because...",
      'The main character of the game has escaped.',
    ],
    secondReplyThoughtLines: ['Wait... is that me?', 'Am I a video game character?'],
    thirdChoices: {
      whatIfNotFound: "Hey... what happens if you don't find him?",
      howToResetConsole: 'How do you reset the console?',
      whereIsAnExit: 'Where is an exit?',
      labCoatQuestion: 'Did you know about the lab coat in the cabinet?',
      niceVoice: 'Nice voice.',
    },
    thirdReplyLines: [
      "If he doesn't turn up and we reset the console...",
      "there's no telling what will happen, but nothing good.",
      'Return to your workstation immediately!',
    ],
    finalChoice: 'Hello?',
    securityAlertLine: 'Security!',
  },
  timbre: {
    lookLines: ['It is a golden doorbell.'],
  },
  officeArrival: {
    caughtLine: 'Police! I found Rocco!',
    welcomeLine: 'I have been waiting for you! Come in.',
    dialogue: {
      firstChoices: [
        { label: 'Hello sir, I am Rocco.', reply: 'Hello sir...' },
        { label: 'Hello, could you tell me how to get out of here?', reply: 'Hello, could you...' },
        { label: 'Your coat is much cleaner than mine.', reply: 'Your coat...' },
        { label: 'You remind me of someone.', reply: 'You remind me...' },
      ],
      firstGuyspriteLines: [
        "I know, you are Rulo, the owner's nephew. I imagined you younger.",
        'My name is Guysprite, Guysprite Treepgood. I am responsible for resetting the game.',
        'Your uncle played a joke on me. He told me you would not arrive until next week.',
      ],
      secondChoices: [
        { label: 'There must be a mistake, I am Rocco.', reply: 'There must be...' },
        { label: 'That is right, he sent me early after all.', reply: 'That is right...' },
        { label: 'How do you reset the console? What is that about?', reply: 'How do you...' },
      ],
      secondGuyspriteLines: [
        'With everything going on, you would not believe it. Everyone is mad.',
        'Rocco, the main character of the game, found a glitch...',
        '...and escaped the game. Now he is wandering around the console...',
        '...and nobody knows where he is...',
        'Have you seen him?',
      ],
      thirdChoices: [
        { label: 'Er... but I am him!', reply: 'Er... but...' },
        { label: 'No, I have not seen him.', reply: 'No, I have...' },
        { label: 'Do you ever let anyone speak?', reply: 'Do you ever...' },
        { label: 'The worst part is that there are people like that.', reply: 'The worst...' },
      ],
      finalGuyspriteLines: [
        'When I spoke to your uncle and he told me you were coming as an intern...',
        '...I was over the moon. We need two people here and they have...',
        '...left me alone since they built all this...',
        '...but you should have seen it before. I built this little kitchen myself. Would you like a coffee?',
      ],
      systemBeepsLine: '[Machine beeps] Beep beep beep beep beep beep...',
      postCoffeeGuyspriteLines: [
        'Oh, it looks like the system has been restored...',
        '...you are perfect timing, let us leave that coffee for later...',
        'Come on, let us go to the other side of the room.',
      ],
      departureReminderLines: [
        'Come on, after you. Let us sit at the controls.',
        'I am right behind you, let us go!',
        'Wait... you... you are Rocco! SECURITY!',
      ],
      guyspriteTalkLine: 'Hurry up!',
      guyspriteLookLines: [
        'He is as talkative as he is nervous.',
        'He talks as much as he trembles.',
        'It looks like the words come out before the thoughts.',
        'He does not stop talking, not even when he breathes.',
        'He is more nervous than a coffee maker about to explode.',
      ],
    },
  },
  officeReading: {
    patienceLabel: 'Guysprite patience',
    startLine: 'Come on, Rulo, read me the first message.',
    correctLine: 'Okay, that is what we will do. And then what does the next message say?',
    secondMessageSecurityLine: 'Okay, show me your ID.',
    incorrectLines: ['Wow, what a strange message!', 'Are you sure that is what they said?'],
    nextLine: 'Read me the next message.',
    repeatedLine: 'Wait, you already read me that message. Are they repeating themselves?',
    repeatedNextLine: 'Read the next message.',
    firstMessageResetLine: 'Okay, I will reset it.',
    firstMessageAlertLines: ['But you are Rocco!', 'Security!'],
    zeroLines: ['But who are you? Security!', 'Wait, you are not Rulo! Security!'],
  },
  doorHandle: {
    lookLines: ['It looks like a mechanism to open the door from the outside.'],
  },
  ascendingPipes: {
    lookLines: [
      'These pipes run from the floor to the ceiling.',
      'This place is packed with them.',
      'They are gray metal and look sturdy.',
      'This one has a wheel valve in the middle.',
    ],
  },
  wheelValve: {
    lookLines: [
      'It is the usual wheel with five metal spokes.',
      'A big, heavy valve wheel.',
      'The spokes are a bit rusty but still firm.',
    ],
    grabLines: ["No way I'm touching anything here, this is about to blow."],
  },
};
